# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Meilisearch installation tasks
  when: meilisearch_enabled | bool
  tags:
    - setup-all
    - setup-meilisearch
    - install-all
    - install-meilisearch
  block:
    - name: Validate Meilisearch configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Meilisearch
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Meilisearch API keys output tasks
  when: meilisearch_enabled | bool
  tags:
    - obtain-api-keys-meilisearch
  block:
    - name: Obtain API keys for Meilisearch
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/obtain_api_keys.yml"

- name: Perform Meilisearch backup tasks
  when: meilisearch_enabled | bool
  tags:
    - backup-meilisearch
  block:
    - name: Run snapshot for Meilisearch
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/snapshots.yml"

- name: Perform Meilisearch uninstallation tasks
  when: not meilisearch_enabled | bool
  tags:
    - setup-all
    - setup-meilisearch
  block:
    - name: Uninstall Meilisearch
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
