# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# The command for obtaining API keys: `ansible-playbook -i inventory/hosts setup.yml --tags=backup-meilisearch -e api_key=YOUR_API_KEY_HERE`

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `api_key` variable needs to be provided via --extra-vars"
  when: "api_key is not defined"

- name: Ensure Meilisearch service is started
  ansible.builtin.service:
    name: "{{ meilisearch_identifier }}"
    state: started
    daemon_reload: true
  register: meilisearch_start

- name: Wait a while, so that Meilisearch can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: meilisearch_start.changed | bool

- name: Run Meilisearch command for creating a snapshot
  ansible.builtin.shell: |
    docker exec --user={{ meilisearch_uid }}:{{ meilisearch_gid }} {{ meilisearch_identifier }} curl -X POST 'http://localhost:7700/snapshots' -H 'Authorization: Bearer {{ api_key }}'
  register: meilisearch_snapshots_result
